Repository mekanism/Mekanism, pull requests merged in 2019-05, with the labels that each got.

#5460 Change unused map (values) to use a set
  src/main/java/mekanism/api/MekanismAPI.java
  src/main/java/mekanism/api/transmitters/DynamicNetwork.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/item/ItemNetworkReader.java
  src/main/java/mekanism/common/tile/transmitter/TileEntityMechanicalPipe.java
  src/main/java/mekanism/common/tile/transmitter/TileEntityPressurizedTube.java
  src/main/java/mekanism/common/tile/transmitter/TileEntityTransmitter.java
  src/main/java/mekanism/common/tile/transmitter/TileEntityUniversalCable.java
  src/main/java/mekanism/common/transmitters/Transmitter.java
  src/main/java/mekanism/common/transmitters/grid/EnergyNetwork.java
  src/main/java/mekanism/common/transmitters/grid/FluidNetwork.java
  src/main/java/mekanism/common/transmitters/grid/GasNetwork.java
  src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
Labels: api, efficiency, enhancement

#5389 Keybindings optimisations
  build.gradle
  src/main/java/mekanism/api/transmitters/TransmissionType.java
  src/main/java/mekanism/client/MekKeyHandler.java
  src/main/java/mekanism/client/MekanismKeyHandler.java
  src/main/java/mekanism/client/render/RenderTickHandler.java
  src/main/java/mekanism/client/render/tileentity/RenderConfigurableMachine.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/fixers/BaseMekanismFixer.java
  src/main/java/mekanism/common/fixers/KeybindingFixer.java
  src/main/java/mekanism/common/fixers/MekanismDataFixers.java
  src/main/java/mekanism/common/fixers/MekanismTEFixer.java
  src/main/java/mekanism/common/fixers/TEFixer.java
  src/main/java/mekanism/common/item/ItemBlockMachine.java
  src/main/java/mekanism/common/item/ItemConfigurator.java
  src/main/java/mekanism/common/item/ItemElectricBow.java
  src/main/java/mekanism/common/item/ItemFlamethrower.java
  src/main/java/mekanism/common/network/PacketItemStack.java
  src/main/java/mekanism/common/util/LangUtils.java
  src/main/java/mekanism/common/util/TextComponentGroup.java
  src/main/java/mekanism/coremod/KeybindingMigrationHelper.java
  src/main/java/mekanism/coremod/MekanismCoremod.java
  src/main/java/mekanism/generators/common/MekanismGenerators.java
  src/main/java/mekanism/generators/common/fixers/GeneratorTEFixer.java
  src/main/resources/assets/mekanism/lang/cs_cz.lang
  src/main/resources/assets/mekanism/lang/da_dk.lang
  src/main/resources/assets/mekanism/lang/de_de.lang
  src/main/resources/assets/mekanism/lang/en_us.lang
  src/main/resources/assets/mekanism/lang/es_es.lang
  src/main/resources/assets/mekanism/lang/fr_fr.lang
  src/main/resources/assets/mekanism/lang/it_it.lang
  src/main/resources/assets/mekanism/lang/ja_jp.lang
  src/main/resources/assets/mekanism/lang/ko_kr.lang
  src/main/resources/assets/mekanism/lang/no_no.lang
  src/main/resources/assets/mekanism/lang/pl_pl.lang
  src/main/resources/assets/mekanism/lang/pt_br.lang
  src/main/resources/assets/mekanism/lang/pt_pt.lang
  src/main/resources/assets/mekanism/lang/ru_ru.lang
  src/main/resources/assets/mekanism/lang/zh_cn.lang
  src/main/resources/assets/mekanism/lang/zh_tw.lang
Labels: Usability, enhancement

#5471 Atomic Disassembler Grass Path Block Tweak
  src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
Labels: enhancement, feature

#5462 Induction matrix optimization
  src/main/java/mekanism/client/gui/GuiInductionMatrix.java
  src/main/java/mekanism/client/gui/GuiMatrixStats.java
  src/main/java/mekanism/common/block/BlockBasic.java
  src/main/java/mekanism/common/block/states/BlockStateBasic.java
  src/main/java/mekanism/common/content/boiler/BoilerUpdateProtocol.java
  src/main/java/mekanism/common/content/matrix/MatrixCache.java
  src/main/java/mekanism/common/content/matrix/MatrixUpdateProtocol.java
  src/main/java/mekanism/common/content/matrix/SynchronizedMatrixData.java
  src/main/java/mekanism/common/content/tank/TankUpdateProtocol.java
  src/main/java/mekanism/common/multiblock/MultiblockManager.java
  src/main/java/mekanism/common/multiblock/UpdateProtocol.java
  src/main/java/mekanism/common/tile/TileEntityEnergyCube.java
  src/main/java/mekanism/common/tile/TileEntityInductionCasing.java
  src/main/java/mekanism/common/tile/TileEntityInductionPort.java
  src/main/java/mekanism/common/tile/TileEntityMultiblock.java
  src/main/java/mekanism/common/util/CableUtils.java
  src/main/java/mekanism/generators/common/content/turbine/TurbineUpdateProtocol.java
Labels: Mekanism: Induction, efficiency, enhancement

#5479 Make Refined Obsidian usable for Nether Portals
  src/main/java/mekanism/common/MekanismBlocks.java
  src/main/java/mekanism/common/block/BlockBasic.java
  src/main/java/mekanism/common/block/states/BlockStateBasic.java
  src/main/resources/mekanism_at.cfg
Labels: feature

#5491 Check ItemStack NBT for comparison in more places
  src/main/java/mekanism/api/infuse/InfuseRegistry.java
  src/main/java/mekanism/client/gui/GuiFormulaicAssemblicator.java
  src/main/java/mekanism/common/base/IFactory.java
  src/main/java/mekanism/common/inventory/InventoryBin.java
  src/main/java/mekanism/common/inventory/container/ContainerFactory.java
  src/main/java/mekanism/common/inventory/container/ContainerMetallurgicInfuser.java
  src/main/java/mekanism/common/item/ItemAtomicDisassembler.java
  src/main/java/mekanism/common/recipe/BinRecipe.java
  src/main/java/mekanism/common/recipe/ingredients/ItemStackMekIngredient.java
  src/main/java/mekanism/common/recipe/outputs/ChanceOutput.java
  src/main/java/mekanism/common/recipe/outputs/ItemStackOutput.java
  src/main/java/mekanism/common/recipe/outputs/PressurizedOutput.java
  src/main/java/mekanism/common/tile/TileEntityBin.java
  src/main/java/mekanism/common/tile/TileEntityDigitalMiner.java
  src/main/java/mekanism/common/tile/TileEntityFactory.java
  src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
  src/main/java/mekanism/common/tile/TileEntityOredictionificator.java
  src/main/java/mekanism/common/tile/prefab/TileEntityAdvancedElectricMachine.java
  src/main/java/mekanism/common/tile/prefab/TileEntityDoubleElectricMachine.java
  src/main/java/mekanism/common/util/StackUtils.java
Labels: enhancement

#5488 Transporter performance improvements
  src/main/java/mekanism/api/infuse/InfuseRegistry.java
  src/main/java/mekanism/client/gui/GuiDigitalMinerConfig.java
  src/main/java/mekanism/client/gui/GuiLogisticalSorter.java
  src/main/java/mekanism/client/gui/GuiSideConfiguration.java
  src/main/java/mekanism/client/render/ColourTemperature.java
  src/main/java/mekanism/client/render/MekanismRenderer.java
  src/main/java/mekanism/client/render/item/basicblock/RenderBasicBlockItem.java
  src/main/java/mekanism/client/render/item/machine/RenderMachineItem.java
  src/main/java/mekanism/client/render/tileentity/RenderConfigurableMachine.java
  src/main/java/mekanism/client/render/tileentity/RenderEnergyCube.java
  src/main/java/mekanism/client/render/tileentity/RenderTeleporter.java
  src/main/java/mekanism/client/render/transmitter/RenderLogisticalTransporter.java
  src/main/java/mekanism/client/render/transmitter/RenderMechanicalPipe.java
  src/main/java/mekanism/client/render/transmitter/RenderTransmitterBase.java
  src/main/java/mekanism/common/CommonWorldTickHandler.java
  src/main/java/mekanism/common/FuelHandler.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/OreDictCache.java
  src/main/java/mekanism/common/Upgrade.java
  src/main/java/mekanism/common/capabilities/CapabilityWrapperManager.java
  src/main/java/mekanism/common/content/transporter/PathfinderCache.java
  src/main/java/mekanism/common/content/transporter/TransitRequest.java
  src/main/java/mekanism/common/content/transporter/TransporterManager.java
  src/main/java/mekanism/common/content/transporter/TransporterPathfinder.java
  src/main/java/mekanism/common/content/transporter/TransporterStack.java
  src/main/java/mekanism/common/integration/crafttweaker/util/RecipeMapModification.java
  src/main/java/mekanism/common/integration/multipart/MultipartTileNetworkJoiner.java
  src/main/java/mekanism/common/item/ItemBlockMachine.java
  src/main/java/mekanism/common/multiblock/MultiblockCache.java
  src/main/java/mekanism/common/multiblock/MultiblockManager.java
  src/main/java/mekanism/common/recipe/ShapedMekanismRecipe.java
  src/main/java/mekanism/common/tile/TileEntityBin.java
  src/main/java/mekanism/common/tile/TileEntityLogisticalSorter.java
  src/main/java/mekanism/common/tile/TileEntityMetallurgicInfuser.java
  src/main/java/mekanism/common/tile/component/TileComponentConfig.java
  src/main/java/mekanism/common/tile/component/TileComponentEjector.java
  src/main/java/mekanism/common/tile/component/TileComponentUpgrade.java
  src/main/java/mekanism/common/tile/prefab/TileEntityBasicBlock.java
  src/main/java/mekanism/common/tile/prefab/TileEntityUpgradeableMachine.java
  src/main/java/mekanism/common/tile/transmitter/TileEntityLogisticalTransporter.java
  src/main/java/mekanism/common/transmitters/TransporterImpl.java
  src/main/java/mekanism/common/transmitters/grid/InventoryNetwork.java
  src/main/java/mekanism/common/util/InventoryUtils.java
  src/main/java/mekanism/common/util/ItemRegistryUtils.java
  src/main/java/mekanism/common/util/RecipeUtils.java
  src/main/java/mekanism/common/util/TransporterUtils.java
  src/main/java/mekanism/generators/client/render/RenderBioGenerator.java
  src/main/java/mekanism/generators/client/render/item/RenderGeneratorItem.java
  src/main/java/mekanism/tools/common/MekanismTools.java
Labels: efficiency
