Repository mekanism/Mekanism, pull requests merged in 2020-01, with the labels that each got.

#5702 Update various templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-issue.md
  .github/PULL_REQUEST_TEMPLATE/general.md
  .github/PULL_REQUEST_TEMPLATE/localization.md
Labels: enhancement

#5727 Create fr_fr.json V0.1
  src/main/resources/assets/mekanism/lang/fr_fr.json
Labels: 1.15

#5758 update zh_cn
  src/main/resources/assets/mekanism/lang/zh_cn.json
  src/main/resources/assets/mekanism/lang/zh_cn.lang
Labels: 1.15, enhancement

#5737 merge with fr_fr_v2
  src/main/resources/assets/mekanism/lang/fr_fr.json
  src/tools/resources/assets/mekanismtools/lang/fr_fr.json
Labels: 1.15, enhancement
