Repository mekanism/Mekanism, pull requests merged in 2021-02, with the labels that each got.

#6948 Add Configuration Card support for Quantum Entangloporter
  src/main/java/mekanism/common/lib/frequency/IFrequencyHandler.java
  src/main/java/mekanism/common/lib/frequency/TileComponentFrequency.java
  src/main/java/mekanism/common/tile/TileEntityQuantumEntangloporter.java
Labels: 1.16, feature, needs review

#6988 Math API Division Optimization
  src/api/java/mekanism/api/MekanismAPI.java
  src/api/java/mekanism/api/math/FloatingLong.java
  src/test/java/mekanism/api/math/FloatingLongPropertyTest.java
  src/test/java/mekanism/api/math/FloatingLongTest.java
Labels: 1.16, efficiency, enhancement

#6994 Create a fake network handler
  src/main/java/mekanism/common/base/MekFakeNetHandler.java
  src/main/java/mekanism/common/base/MekFakePlayer.java
Labels: 1.16, enhancement
