Repository mekanism/Mekanism, pull requests merged in 2022-05, with the labels that each got.

#7446 [1.18.x] Curio jetpack
  build.gradle
  gradle.properties
  src/main/java/mekanism/client/ClientTickHandler.java
  src/main/java/mekanism/client/key/MekanismKeyHandler.java
  src/main/java/mekanism/client/render/MekanismCurioRenderer.java
  src/main/java/mekanism/client/render/hud/MekaSuitHUD.java
  src/main/java/mekanism/common/CommonPlayerTickHandler.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/content/gear/mekasuit/ModuleChargeDistributionUnit.java
  src/main/java/mekanism/common/integration/MekanismHooks.java
  src/main/java/mekanism/common/integration/curios/CuriosIntegration.java
  src/main/java/mekanism/common/item/gear/ItemJetpack.java
  src/main/java/mekanism/common/item/interfaces/IGasItem.java
  src/main/java/mekanism/common/item/interfaces/IItemHUDProvider.java
  src/main/java/mekanism/common/network/PacketHandler.java
  src/main/java/mekanism/common/network/to_server/PacketModeChangeCurios.java
  src/main/java/mekanism/common/tile/TileEntityChargepad.java
  src/main/resources/META-INF/mods.toml
Labels: enhancement, 1.18

#7469 Added gyroscopic stabilization unit
  src/datagen/generated/mekanism/.cache/cache
  src/datagen/generated/mekanism/assets/mekanism/lang/en_ud.json
  src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
  src/datagen/generated/mekanism/assets/mekanism/models/item/module_gyroscopic_stabilization_unit.json
  src/datagen/generated/mekanism/data/mekanism/recipes/module_gyroscopic_stabilization_unit.json
  src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
  src/datagen/main/java/mekanism/common/recipe/impl/MekanismRecipeProvider.java
  src/main/java/mekanism/common/CommonPlayerTickHandler.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/registries/MekanismItems.java
  src/main/java/mekanism/common/registries/MekanismModules.java
  src/main/resources/assets/mekanism/textures/item/module_gyroscopic_stabilization_unit.png
Labels: feature, 1.18

#7468 Added raw block recipes and organized existing recipes
  src/datagen/generated/mekanism/.cache/cache
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/copper/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/gold/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/iron/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/lead/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/osmium/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/tin/slurry/dirty/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/clump/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/dust/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/shard/from_raw_block.json
  src/datagen/generated/mekanism/data/mekanism/recipes/processing/uranium/slurry/dirty/from_raw_block.json
  src/datagen/main/java/mekanism/common/recipe/impl/OreProcessingRecipeProvider.java
Labels: needs review, 1.18

#7479 Fix floating cuboid in Atomic Disassembler model
  src/main/java/mekanism/client/model/ModelAtomicDisassembler.java
Labels: bug, confirmed, aesthetic, 1.18

#7477 Added the Hydrostatic Repulsor Unit
  src/datagen/generated/mekanism/.cache/cache
  src/datagen/generated/mekanism/assets/mekanism/lang/en_ud.json
  src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
  src/datagen/generated/mekanism/assets/mekanism/models/item/module_hydrostatic_repulsor_unit.json
  src/datagen/generated/mekanism/data/mekanism/recipes/module_hydrostatic_repulsor_unit.json
  src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
  src/datagen/main/java/mekanism/common/recipe/impl/MekanismRecipeProvider.java
  src/main/java/mekanism/common/CommonPlayerTickHandler.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/MekanismLang.java
  src/main/java/mekanism/common/base/PlayerState.java
  src/main/java/mekanism/common/config/GearConfig.java
  src/main/java/mekanism/common/content/gear/mekasuit/ModuleHydrostaticRepulsorUnit.java
  src/main/java/mekanism/common/registries/MekanismItems.java
  src/main/java/mekanism/common/registries/MekanismModules.java
  src/main/resources/assets/mekanism/textures/item/module_hydrostatic_repulsor_unit.png
Labels: feature, 1.18

#7473 Added blasting unit
  src/datagen/generated/mekanism/.cache/cache
  src/datagen/generated/mekanism/assets/mekanism/lang/en_ud.json
  src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
  src/datagen/generated/mekanism/assets/mekanism/models/item/module_blasting_unit.json
  src/datagen/generated/mekanism/data/mekanism/recipes/module_blasting_unit.json
  src/datagen/main/java/mekanism/client/lang/MekanismLangProvider.java
  src/datagen/main/java/mekanism/common/recipe/impl/MekanismRecipeProvider.java
  src/main/java/mekanism/client/render/RenderTickHandler.java
  src/main/java/mekanism/common/CommonPlayerTickHandler.java
  src/main/java/mekanism/common/Mekanism.java
  src/main/java/mekanism/common/MekanismLang.java
  src/main/java/mekanism/common/base/ProfilerConstants.java
  src/main/java/mekanism/common/content/gear/IBlastingItem.java
  src/main/java/mekanism/common/content/gear/mekatool/ModuleBlastingUnit.java
  src/main/java/mekanism/common/content/gear/mekatool/ModuleVeinMiningUnit.java
  src/main/java/mekanism/common/item/gear/ItemAtomicDisassembler.java
  src/main/java/mekanism/common/item/gear/ItemMekaTool.java
  src/main/java/mekanism/common/registries/MekanismItems.java
  src/main/java/mekanism/common/registries/MekanismModules.java
  src/main/java/mekanism/common/util/MekanismUtils.java
  src/main/java/mekanism/common/util/MultipartUtils.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/mekanism/textures/item/module_blasting_unit.png
Labels: feature, 1.18
